### ISSUE TITLE
Remove task of binding containerd defautl to crictl

### ISSUE THREAD

**Issue by bissquit** [cloud-labs-infra/ansible-k8s-cluster#44]
**Is your feature request related to a problem? Please describe.**
Remove the following task from role:
```yaml
    - name: Make containerd defautl to crictl
      ansible.builtin.copy:
        content: "runtime-endpoint: unix:///var/run/containerd/containerd.sock\n"
        dest: /etc/crictl.yaml
        owner: root
        group: root
        mode: 0640
```
It's not connected with kubernetes itself rather with containerd installation.

**Describe the solution you'd like**
I see the following solutions:
1. Remove from role completely and nothing else
2. Remove from role and possibly add to readme as a note
3. Write your own role with `crictl` installation following [official docs](https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md). We also could use third-party role e.g. [ansible-role-crictl](https://github.com/darkwizard242/ansible-role-crictl)

**Describe alternatives you've considered**
Not applicable

**Additional context**
Not applicable
