### ISSUE TITLE
`Check nodes until ready` task fails because of wrong node name

### ISSUE THREAD

**Issue by bissquit** [cloud-labs-infra/ansible-k8s-cluster#49]
**Description**
`Check nodes until ready` task fails because of wrong node name.

Maybe the possible solution would be adding `name:` fileld in [NodeRegistrationOptions ](https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/#kubeadm-k8s-io-v1beta3-NodeRegistrationOptions) configuration both for init- and join- configuration like so:

```yaml
k8s_cluster_join_configuration:
  nodeRegistration:
    name: "{{ inventory_hostname }}"
    ignorePreflightErrors:
      - SystemVerification
...
```

And also change respective value in the task:

```yaml
- name: Check nodes until ready
  ansible.builtin.shell: |
    kubectl get node {{ inventory_hostname }} \
      --kubeconfig=/etc/kubernetes/admin.conf -o json | jq -Mr '.status.conditions[4].status'
  register: kubectl_response
  changed_when: false
  delegate_to: "{{ k8s_cluster_init_main_node_hostname }}"
  until: kubectl_response.stdout == "True"
  retries: 48
  delay: 5

```

**Steps to reproduce**

1. Set the name of node with dots like `worker-1.k8s.domain.local`
2. Play will fail on task `Check nodes until ready` with the following error:

```text
Error from server (NotFound): nodes \"worker-1\" not found
```

But node will be joined successfully despite of failed play

**Expected behavior**
Task works as expected and receives right node name

**Environment:**
- OS (output of `uname -a`)

```text
Linux master-1 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
 - Ansible version (output of `ansible --version`, any sensitive information e.g. username may be removed)

```text
ansible [core 2.13.0]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```
 - Any useful information (e.g. env is a Docker container)
 No

**Additional context**
Not applicable
